import{a as A,S,i as n}from"./assets/vendor-CIu9XFSi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&s(f)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const q="52813503-cb7190d9096228e90c42c3654",M="https://pixabay.com/api/",$=15;async function L(i,o=1){try{return(await A.get(M,{params:{key:q,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:$}})).data}catch(e){throw e}}const h=document.querySelector(".gallery"),l=document.querySelector(".loader"),c=document.querySelector(".js-load-more");let d=null;function w(i){if(!h){console.warn("Gallery element not found in DOM");return}const o=i.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img
              src="${e.webformatURL}"
              alt="${e.tags}"
              loading="lazy"
              width="300"
            />
          </a>
          <ul class="info">
            <li><b>Likes:</b> ${e.likes}</li>
            <li><b>Views:</b> ${e.views}</li>
            <li><b>Comments:</b> ${e.comments}</li>
            <li><b>Downloads:</b> ${e.downloads}</li>
          </ul>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",o),d?d.refresh():d=new S(".gallery a",{captionsData:"alt",captionDelay:250})}function B(){h&&(h.innerHTML="",d&&(d.destroy(),d=null))}function E(){l&&(l.classList.remove("hidden"),l.setAttribute("aria-hidden","false"))}function P(){l&&(l.classList.add("hidden"),l.setAttribute("aria-hidden","true"))}function R(){c&&(c.classList.remove("hidden"),c.disabled=!1)}function a(){c&&(c.classList.add("hidden"),c.disabled=!0)}const m=document.querySelector(".form"),g=document.querySelector(".js-load-more"),p=document.querySelector(".gallery");let u=1,b="",y=0;const v=15;a();g==null||g.addEventListener("click",O);m==null||m.addEventListener("submit",H);async function H(i){i.preventDefault();const o=i.target.elements["search-text"].value.trim();if(!o){n.error({title:"Error",message:"Please enter a search word!",position:"topRight"});return}b=o,u=1,B(),a(),E();try{const e=await L(b,u),s=Array.isArray(e.hits)?e.hits:[];if(y=Number.isFinite(e.totalHits)?e.totalHits:0,!s.length){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a();return}w(s),u*v<y?R():(a(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){console.error(e),n.error({title:"Error",message:"Failed to fetch images. Try again!",position:"topRight"})}finally{P()}}async function O(){var o;E(),a();const i=u+1;try{const e=await L(b,i),s=Array.isArray(e.hits)?e.hits:[];if(!s.length){a(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}w(s),u=i;const t=p==null?void 0:p.firstElementChild,r=((o=t==null?void 0:t.getBoundingClientRect)==null?void 0:o.call(t).height)??0;r>0&&window.scrollBy({top:r*2,behavior:"smooth"});const f=y?Math.ceil(y/v):0;u>=f?(a(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):R()}catch(e){console.error(e),n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{P()}}
//# sourceMappingURL=index.js.map
